lichess.study = {
  study: {
    id: "o1p8SH7f",
    name: "100 Finais que você deve saber.",
    members: {
      robstelling: {
        user: { name: "RobStelling", id: "robstelling" },
        role: "w",
      },
      raoni: { user: { name: "Raoni", patron: true, id: "raoni" }, role: "w" },
    },
    position: { chapterId: "g6tNx32F", path: "" },
    ownerId: "raoni",
    settings: {
      computer: "everyone",
      explorer: "everyone",
      cloneable: "owner",
      chat: "member",
      sticky: true,
      description: false,
    },
    visibility: "public",
    createdAt: 1586055924820,
    secondsSinceUpdate: 1563781,
    from: "scratch",
    likes: 185,
    liked: false,
    features: {
      cloneable: false,
      chat: false,
      sticky: true,
      description: false,
    },
    topics: ["Final"],
    chapters: [
      { id: "g6tNx32F", name: "GUIA" },
      { id: "ibu8kC5N", name: "1. FINAIS BÁSICOS" },
      {
        id: "7vZgYx5B",
        name: "FINAL 1 (posições 1.1 e 1.2) - A regra do quadrado",
        res: "1-0",
      },
      { id: "JEvVmAbw", name: "Posição 1.3 - A regra do quadrado" },
      { id: "bQHsCh3J", name: "TESTE" },
      {
        id: "ojO3t6LO",
        name: "FINAL 2 (Posição 1.4) - O peão está na 6ª posição",
      },
      { id: "85C80TRc", name: "TESTE" },
      { id: "GufmXMA4", name: "Posição 1.5 - O peão está na 6ª posição" },
      { id: "PS2KjTXj", name: "TESTE" },
      { id: "AvsMOylt", name: "Posição 1.6 - O peão está na 6ª posição" },
      { id: "nUmX0lhF", name: "TESTE" },
      {
        id: "YFETO7OG",
        name: "Posição 1.7 - O peão está na 6ª posição",
        res: "1-0",
      },
      { id: "T5NIbKhx", name: "TESTE", res: "1-0" },
      { id: "d4a7h1XO", name: "Posição 1.8 - O peão está na 6ª posição" },
      { id: "ujAlYTIm", name: "TESTE" },
      { id: "Nzqoev4H", name: "FINAL 3 - Posição 1.9 - Casas Críticas" },
      { id: "3f4KraR1", name: "TESTE" },
      { id: "0tNLwmIt", name: "Posição 1.10 - Casas Críticas" },
      { id: "fJGRZUVd", name: "TESTE" },
      { id: "bWWub0cZ", name: "Posição 1.11 - Casas Críticas" },
      { id: "X5rL8Tou", name: "TESTE" },
      { id: "RwTKQvPw", name: "Posição 1.12 - Casas Críticas" },
      { id: "DT9W2dEx", name: "TESTE" },
      { id: "bjlq5QQP", name: "Posição 1.13 - Casas Críticas" },
      { id: "6FiZkLMC", name: "TESTE", res: "1-0" },
      {
        id: "oG4sM91I",
        name:
          "FINAL 4 (Posição 1.14) - O peão da torre. Defendendo o rei na frente do peão",
      },
      { id: "qgbGGiXN", name: "Posição 1.15 - O peão da torre." },
      {
        id: "L5mqnt1S",
        name: "FINAL 5 (Posição 1.16) - Aprisionando o rei do lado mais forte",
      },
      { id: "NzLGblSO", name: "TESTE" },
      {
        id: "qLYhcymR",
        name: "FINAL 6 (Posição 1.17) - Torre vs. Bispo - O canto mau",
      },
      { id: "1cUeQ1wm", name: "TESTE" },
      {
        id: "dY5JeOT3",
        name: "FINAL 7 (Posição 1.18) - Torre vs. Bispo - O canto bom",
      },
      { id: "8mxUfuum", name: "TESTE" },
      {
        id: "T1WSTEBL",
        name:
          "FINAL 8. (Posições 1.19 e 1.20) - Torre vs. Cavalo - Na borda do tabuleiro",
      },
      { id: "xPN1s0Pl", name: "TESTE" },
      {
        id: "tmU88Pn5",
        name: "FINAL 9 (Posição 1.21) - Torre vs. Cavalo - No canto",
      },
      {
        id: "dLAuHLHB",
        name: "Posições 1.24 e 1.25 - Kamsky vs. Bacrot - Sofia 2006",
      },
      { id: "c1EZaCBT", name: "CAPÍTULO 2 - TESTES BÁSICOS" },
      { id: "RoEfTfky", name: "Exercício 1" },
      { id: "aTO6yP5M", name: "Exercício 2" },
      { id: "x9JegExj", name: "Exercício 3" },
      { id: "1JjXme8W", name: "Exercício 4" },
      { id: "joTZmH7Q", name: "Exercício 5" },
      { id: "qQ6Xf4v7", name: "Exercício 6" },
      { id: "pWvkNX2W", name: "Exercício 7" },
      { id: "PMsQIf3G", name: "Exercício 8" },
      { id: "WVgpMxdY", name: "Exercício 9" },
      { id: "up62M0n3", name: "Exercício 10" },
      { id: "t4sK24TN", name: "Exercício 11" },
      { id: "GuBmivjq", name: "Exercício 12" },
      { id: "lECOcPaz", name: "Exercício 13" },
      { id: "PmHHlcLN", name: "Exercício 14" },
      { id: "4IUkenkv", name: "Exercício 15" },
      { id: "bhqDlTb1", name: "Exercício 16" },
      { id: "CO7cz6Ic", name: "Exercício 17" },
      { id: "ZHHyOQ53", name: "Exercício 18" },
      { id: "Mw8nnqkQ", name: "Exercício 19" },
      { id: "aXtGAsh3", name: "Exercício 20" },
      { id: "osiCGglF", name: "Exercício 21" },
      { id: "Wv2JawpS", name: "Exercício 22" },
      { id: "PFLMFCBe", name: "Exercício 23" },
      { id: "JVRl6cTj", name: "Exercício 24" },
      { id: "zFAauVp1", name: "Exercício 25" },
      { id: "zLlWecw5", name: "Exercício 26" },
    ],
    chapter: {
      id: "bQHsCh3J",
      ownerId: "raoni",
      setup: {
        variant: { key: "fromPosition", name: "From Position" },
        orientation: "white",
        fromFen: true,
      },
      tags: [],
      features: { computer: true, explorer: true },
      gamebook: true,
    },
    description: "",
    chat: {
      lines: [
        { u: "Raoni", t: "Espero que gostem" },
        { u: "Galucadasial", t: "aproveitando mto kkk" },
        { u: "Galucadasial", t: "vai fazer mais finais?" },
        {
          u: "Raoni",
          t:
            "Vou tentar trabalhar nesse projeto. Caso a galera goste eu produzirei o restante do livro",
        },
        { u: "Galucadasial", t: "blz" },
        { u: "cdrsantos", t: "Estava pensando em trabalhar com esse livro" },
        { u: "WanSilence", t: "Bom trabalho, excelente projeto." },
        { u: "cdrsantos", t: "você já finalizou o trabalho ou esta no começo" },
        { u: "Raoni", t: "No começo" },
        { u: "Raoni", t: "Terminei hoje esses dois capítulos do livro" },
        {
          u: "Raoni",
          t: "pra cada caso eu coloquei um treino pra pessoa fixar melhor",
        },
        { u: "Raoni", t: "O capítulo 2 é só de Teste, como vcs podem ver." },
        {
          u: "Raoni",
          t: "Livro é bom, mas a gente não consegue mover as peças. :-)",
        },
        {
          u: "Raoni",
          t:
            "Por isso, o modo interativo é o que mais rende em questão de estudo.",
        },
        {
          u: "cdrsantos",
          t:
            "eu achei esse trabalho em Inglês e comecei a tradução para depois ir montando as posições",
        },
        { u: "Raoni", t: "A pessoa aprende mais e de maneira rápida." },
        { u: "Raoni", t: "Muito bom, cdrsantos!" },
        {
          u: "cdrsantos",
          t: "Você consegue acompanhar por ai os meus movimentos",
        },
        { u: "Raoni", t: "Não" },
        { u: "Raoni", t: "Lembrem de abrir esse estudo pelo navegador." },
        {
          u: "Raoni",
          t: "Abrindo pelo Aplicativo não funciona o modo interativo",
        },
        { u: "cdrsantos", t: "Tem que abrir  em Notebook ou PC, e isso" },
        { u: "Raoni", t: "sim." },
        { u: "Raoni", t: "se não tiver, abre pelo navegador do celular" },
        { u: "Raoni", t: "não fica 100% mas fica no modo correto" },
        { u: "Raoni", t: "só não funciona pelo aplicativo mesmo" },
        { u: "Raoni", t: "lichess ainda não permite" },
        { u: "cdib", t: "Valew !!" },
        {
          u: "JoaoMoreira47",
          t:
            "Muito bom esse estudos, meu amigo esta de parabens, faça mais por favor!",
        },
        { u: "Raoni", t: "Estudo Lotado" },
        { u: "Raoni", t: "Galera se interssou. Vou fazer o curso completo" },
        { u: "Raoni", t: "*Interessou" },
        { u: "Raoni", t: "Criei um grupo para tratar somente deste assunto" },
        { u: "Raoni", t: "https://chat.whatsapp.com/J6M0Cb0q0pD1UwWIGgipxN" },
        {
          u: "Torre_azul",
          t: "Excelente material amigo Raoni. Muito criativo e legal. Parabéns",
        },
        {
          u: "Raoni",
          t:
            "https://www.youtube.com/channel/UC10omdo9f479xhAmA_xLNIw?view_as=subscriber",
        },
        { u: "Raoni", t: "Não esqueça de deixar o like aqui no estudo" },
        { u: "Raoni", t: "parte 2" },
        { u: "Raoni", t: "https://lichess.org/study/E8pSmida" },
        {
          u: "Raoni",
          t:
            "Quem quiser ter acesso a todas as partes é só enviar mensagem pelo chat aqui do lichess mesmo",
        },
      ],
      writeable: false,
    },
  },
  analysis: {
    game: {
      id: "synthetic",
      variant: { key: "fromPosition", name: "From Position", short: "FEN" },
      opening: null,
      fen: "8/4k3/2K5/8/8/8/1P6/8 w - - 0 1",
      turns: 0,
      player: "white",
      status: { id: 10, name: "created" },
      initialFen: "8/4k3/2K5/8/8/8/1P6/8 w - - 0 1",
    },
    player: { id: null, color: "white" },
    opponent: { color: "black", ai: null },
    orientation: "white",
    pref: {
      animationDuration: 300,
      coords: 1,
      moveEvent: 2,
      showCaptured: true,
      rookCastle: true,
      highlight: true,
      destination: true,
    },
    path: 0,
    userAnalysis: true,
    treeParts: [
      {
        ply: 0,
        fen: "8/4k3/2K5/8/8/8/1P6/8 w - - 0 1",
        comments: [
          {
            id: "5aLG",
            text: "Procure o melhor lance para as brancas.",
            by: { id: "raoni", name: "Raoni" },
          },
        ],
        dests: "QYIPXHJ jrz",
      },
      {
        ply: 1,
        fen: "8/2K1k3/8/8/8/8/1P6/8 b - - 1 1",
        id: "MU",
        uci: "c6c7",
        san: "Kc7",
      },
      {
        ply: 2,
        fen: "8/2K5/4k3/8/8/8/1P6/8 w - - 2 2",
        id: "WO",
        uci: "e7e6",
        san: "Ke6",
        comments: [
          {
            id: "9eh7",
            text: "Procure o melhor lance para as brancas.",
            by: { id: "raoni", name: "Raoni" },
          },
        ],
      },
      {
        ply: 3,
        fen: "8/2K5/4k3/8/1P6/8/8/8 b - - 0 2",
        id: ",<",
        uci: "b2b4",
        san: "b4",
      },
      {
        ply: 4,
        fen: "8/2K5/8/3k4/1P6/8/8/8 w - - 1 3",
        id: "OF",
        uci: "e6d5",
        san: "Kd5",
        comments: [
          {
            id: "zN9a",
            text: "Procure o melhor lance para as brancas.",
            by: { id: "raoni", name: "Raoni" },
          },
        ],
      },
      {
        ply: 5,
        fen: "8/2K5/8/1P1k4/8/8/8/8 b - - 0 3",
        id: "<D",
        uci: "b4b5",
        san: "b5",
      },
      {
        ply: 6,
        fen: "8/2K5/8/1Pk5/8/8/8/8 w - - 1 4",
        id: "FE",
        uci: "d5c5",
        san: "Kc5",
        comments: [
          {
            id: "pvTS",
            text: "Procure o melhor lance para as brancas.",
            by: { id: "raoni", name: "Raoni" },
          },
        ],
      },
      {
        ply: 7,
        fen: "8/2K5/1P6/2k5/8/8/8/8 b - - 0 4",
        id: "DL",
        uci: "b5b6",
        san: "b6",
        comments: [
          {
            id: "pZYk",
            text: "Parabéns! Você completou esta lição.",
            by: { id: "raoni", name: "Raoni" },
          },
        ],
        shapes: [
          { brush: "green", orig: "b6", dest: "b8" },
          { brush: "green", orig: "b6" },
        ],
      },
    ],
  },
};
